
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[[exemptions.autocfg]]
version = "1.5.1"
criteria = "safe-to-run"

[[exemptions.bitflags]]
version = "2.13.2"
criteria = "safe-to-run"

[[exemptions.cfg-if]]
version = "1.0.5"
criteria = "safe-to-run"

[[exemptions.getrandom]]
version = "0.3.4"
criteria = "safe-to-run"

[[exemptions.libc]]
version = "0.2.190"
criteria = "safe-to-run"

[[exemptions.proc-macro2]]
version = "1.0.107"
criteria = "safe-to-run"

[[exemptions.proptest]]
version = "1.11.0"
criteria = "safe-to-run"

[[exemptions.r-efi]]
version = "5.3.0"
criteria = "safe-to-run"

[[exemptions.rand]]
version = "0.9.5"
criteria = "safe-to-run"

[[exemptions.rand_chacha]]
version = "0.9.0"
criteria = "safe-to-run"

[[exemptions.rand_core]]
version = "0.9.5"
criteria = "safe-to-run"

[[exemptions.regex-syntax]]
version = "0.8.11"
criteria = "safe-to-run"

[[exemptions.syn]]
version = "2.0.119"
criteria = "safe-to-run"

[[exemptions.unicode-ident]]
version = "1.0.26"
criteria = "safe-to-run"

[[exemptions.wit-bindgen]]
version = "0.57.1"
criteria = "safe-to-run"

[[exemptions.zerocopy]]
version = "0.8.59"
criteria = "safe-to-run"

[[exemptions.zerocopy-derive]]
version = "0.8.59"
criteria = "safe-to-run"
